import java.util.*;

/** Class to count frequencies of the words generated by an
 *   iterator.
 * @author CS2510
 * @version 11-09-2013 
 */
public class WordCounter{
    /* ... FILL IN ... */
    
    /**
     * The default constructor
     */
    public WordCounter(){ }
    
    /** record the words generated by the given iterator
     * @param it the given iterator over the input text
     */
    public void countWords(Iterator<Word> it){
        /* ... FILL IN ... */
    }
    
    /** Count the number of different words in this Counter 
     * @return the count of different words in this Counter
     */
    public int words(){
        /* ... FILL IN ... */
        return 0;
    }  
    
    /** Print the words and their frequencies for the top n words 
     * @param n the numebr of words to print
     */
    public void printWords(int n){
        /* ... FILL IN ... */
    }  
}
