#AnimateKeys.py

import maya.cmds as cmds

cmds.cutKey( 'Hand_Left', time=(0,800) )
cmds.cutKey( 'Hand_Right', time=(0,800) )
cmds.cutKey( 'Hips', time=(0,800) )
cmds.cutKey( 'Iris_Left', time=(0,800) )
cmds.cutKey( 'Iris_Right', time=(0,800) )
cmds.cutKey( 'persp', time=(0,800) )

cmds.setKeyframe( 'Hand_Left',  time=0, attribute='rz', value=0 )
cmds.setKeyframe( 'Hand_Right', time=0, attribute='rz', value=0 )
cmds.setKeyframe( 'Hips',       time=0, attribute='rz', value=0 )
cmds.setKeyframe( 'Hips',       time=0, attribute='tz', value=0 )
cmds.setKeyframe( 'Iris_Left',  time=0, attribute='scaleX', value=1 )
cmds.setKeyframe( 'Iris_Left',  time=0, attribute='scaleZ', value=1 )
cmds.setKeyframe( 'Iris_Right', time=0, attribute='scaleX', value=1 )
cmds.setKeyframe( 'Iris_Right', time=0, attribute='scaleZ', value=1 )

cmds.setKeyframe( 'Hand_Left',  time=100, attribute='rz', value=20 )
cmds.setKeyframe( 'Hand_Right', time=100, attribute='rz', value=20 )
cmds.setKeyframe( 'Iris_Left',  time=100, attribute='scaleX', value=0.5 )
cmds.setKeyframe( 'Iris_Left',  time=100, attribute='scaleZ', value=0.5 )
cmds.setKeyframe( 'Iris_Right', time=100, attribute='scaleX', value=0.5 )
cmds.setKeyframe( 'Iris_Right', time=100, attribute='scaleZ', value=0.5 )

cmds.setKeyframe( 'Hand_Left',  time=200, attribute='rz', value=0 )
cmds.setKeyframe( 'Hand_Right', time=200, attribute='rz', value=0 )
cmds.setKeyframe( 'Hips',       time=200, attribute='rz', value=10 )
cmds.setKeyframe( 'Hips',       time=200, attribute='tz', value=2 )
cmds.setKeyframe( 'Iris_Left',  time=200, attribute='scaleX', value=1 )
cmds.setKeyframe( 'Iris_Left',  time=200, attribute='scaleZ', value=1 )
cmds.setKeyframe( 'Iris_Right', time=200, attribute='scaleX', value=1 )
cmds.setKeyframe( 'Iris_Right', time=200, attribute='scaleZ', value=1 )

cmds.setKeyframe( 'Hand_Left',  time=300, attribute='rz', value=-20 )
cmds.setKeyframe( 'Hand_Right', time=300, attribute='rz', value=-20 )
cmds.setKeyframe( 'Iris_Left',  time=300, attribute='scaleX', value=0.5 )
cmds.setKeyframe( 'Iris_Left',  time=300, attribute='scaleZ', value=0.5 )
cmds.setKeyframe( 'Iris_Right', time=300, attribute='scaleX', value=0.5 )
cmds.setKeyframe( 'Iris_Right', time=300, attribute='scaleZ', value=0.5 )

cmds.setKeyframe( 'Hand_Left',  time=400, attribute='rz', value=0 )
cmds.setKeyframe( 'Hand_Right', time=400, attribute='rz', value=0 )
cmds.setKeyframe( 'Hips',       time=400, attribute='rz', value=0 )
cmds.setKeyframe( 'Hips',       time=400, attribute='tz', value=0 )
cmds.setKeyframe( 'Iris_Left',  time=400, attribute='scaleX', value=1 )
cmds.setKeyframe( 'Iris_Left',  time=400, attribute='scaleZ', value=1 )
cmds.setKeyframe( 'Iris_Right', time=400, attribute='scaleX', value=1 )
cmds.setKeyframe( 'Iris_Right', time=400, attribute='scaleZ', value=1 )

cmds.setKeyframe( 'Hand_Left',  time=500, attribute='rz', value=20 )
cmds.setKeyframe( 'Hand_Right', time=500, attribute='rz', value=20 )
cmds.setKeyframe( 'Iris_Left',  time=500, attribute='scaleX', value=0.5 )
cmds.setKeyframe( 'Iris_Left',  time=500, attribute='scaleZ', value=0.5 )
cmds.setKeyframe( 'Iris_Right', time=500, attribute='scaleX', value=0.5 )
cmds.setKeyframe( 'Iris_Right', time=500, attribute='scaleZ', value=0.5 )

cmds.setKeyframe( 'Hand_Left',  time=600, attribute='rz', value=0 )
cmds.setKeyframe( 'Hand_Right', time=600, attribute='rz', value=0 )
cmds.setKeyframe( 'Hips',       time=600, attribute='rz', value=-10 )
cmds.setKeyframe( 'Hips',       time=600, attribute='tz', value=-2 )
cmds.setKeyframe( 'Iris_Left',  time=600, attribute='scaleX', value=1 )
cmds.setKeyframe( 'Iris_Left',  time=600, attribute='scaleZ', value=1 )
cmds.setKeyframe( 'Iris_Right', time=600, attribute='scaleX', value=1 )
cmds.setKeyframe( 'Iris_Right', time=600, attribute='scaleZ', value=1 )

cmds.setKeyframe( 'Hand_Left',  time=700, attribute='rz', value=-20 )
cmds.setKeyframe( 'Hand_Right', time=700, attribute='rz', value=-20 )
cmds.setKeyframe( 'Iris_Left',  time=700, attribute='scaleX', value=0.5 )
cmds.setKeyframe( 'Iris_Left',  time=700, attribute='scaleZ', value=0.5 )
cmds.setKeyframe( 'Iris_Right', time=700, attribute='scaleX', value=0.5 )
cmds.setKeyframe( 'Iris_Right', time=700, attribute='scaleZ', value=0.5 )

cmds.setKeyframe( 'Hand_Left',  time=800, attribute='rz', value=0 )
cmds.setKeyframe( 'Hand_Right', time=800, attribute='rz', value=0 )
cmds.setKeyframe( 'Hips',       time=800, attribute='rz', value=0 )
cmds.setKeyframe( 'Hips',       time=800, attribute='tz', value=0 )
cmds.setKeyframe( 'Iris_Left',  time=800, attribute='scaleX', value=1 )
cmds.setKeyframe( 'Iris_Left',  time=800, attribute='scaleZ', value=1 )
cmds.setKeyframe( 'Iris_Right', time=800, attribute='scaleX', value=1 )
cmds.setKeyframe( 'Iris_Right', time=800, attribute='scaleZ', value=1 )

cmds.setKeyframe( 'persp', time=1, attribute='tx', value=42 )
cmds.setKeyframe( 'persp', time=1, attribute='ty', value=15 )
cmds.setKeyframe( 'persp', time=1, attribute='tz', value=28 )
cmds.setKeyframe( 'persp', time=1, attribute='rx', value=-18 )
cmds.setKeyframe( 'persp', time=1, attribute='ry', value=56 )
cmds.setKeyframe( 'persp', time=1, attribute='rz', value=0 )

cmds.setKeyframe( 'persp', time=200, attribute='tx', value=37 )
cmds.setKeyframe( 'persp', time=200, attribute='ty', value=-20 )
cmds.setKeyframe( 'persp', time=200, attribute='tz', value=37 )
cmds.setKeyframe( 'persp', time=200, attribute='rx', value=17 )
cmds.setKeyframe( 'persp', time=200, attribute='ry', value=41 )
cmds.setKeyframe( 'persp', time=200, attribute='rz', value=0 )

cmds.setKeyframe( 'persp', time=400, attribute='tx', value=37 )
cmds.setKeyframe( 'persp', time=400, attribute='ty', value=-20 )
cmds.setKeyframe( 'persp', time=400, attribute='tz', value=37 )
cmds.setKeyframe( 'persp', time=400, attribute='rx', value=17 )
cmds.setKeyframe( 'persp', time=400, attribute='ry', value=41 )
cmds.setKeyframe( 'persp', time=400, attribute='rz', value=0 )

cmds.setKeyframe( 'persp', time=410, attribute='tx', value=-10 )
cmds.setKeyframe( 'persp', time=410, attribute='ty', value=11 )
cmds.setKeyframe( 'persp', time=410, attribute='tz', value=15 )
cmds.setKeyframe( 'persp', time=410, attribute='rx', value=-12 )
cmds.setKeyframe( 'persp', time=410, attribute='ry', value=-31 )
cmds.setKeyframe( 'persp', time=410, attribute='rz', value=0 )

cmds.setKeyframe( 'persp', time=590, attribute='tx', value=-10 )
cmds.setKeyframe( 'persp', time=590, attribute='ty', value=11 )
cmds.setKeyframe( 'persp', time=590, attribute='tz', value=15 )
cmds.setKeyframe( 'persp', time=590, attribute='rx', value=-12 )
cmds.setKeyframe( 'persp', time=590, attribute='ry', value=-31 )
cmds.setKeyframe( 'persp', time=590, attribute='rz', value=0 )

cmds.setKeyframe( 'persp', time=600, attribute='tx', value=42 )
cmds.setKeyframe( 'persp', time=600, attribute='ty', value=15 )
cmds.setKeyframe( 'persp', time=600, attribute='tz', value=28 )
cmds.setKeyframe( 'persp', time=600, attribute='rx', value=-18 )
cmds.setKeyframe( 'persp', time=600, attribute='ry', value=56 )
cmds.setKeyframe( 'persp', time=600, attribute='rz', value=0 )

cmds.setKeyframe( 'persp', time=800, attribute='tx', value=42 )
cmds.setKeyframe( 'persp', time=800, attribute='ty', value=15 )
cmds.setKeyframe( 'persp', time=800, attribute='tz', value=28 )
cmds.setKeyframe( 'persp', time=800, attribute='rx', value=-18 )
cmds.setKeyframe( 'persp', time=800, attribute='ry', value=56 )
cmds.setKeyframe( 'persp', time=800, attribute='rz', value=0 )

cmds.keyTangent( 'Hand_Right', inTangentType='clamped', outTangentType='clamped' )
cmds.keyTangent( 'Hand_Left', inTangentType='clamped', outTangentType='clamped' )
cmds.keyTangent( 'Hips', inTangentType='clamped', outTangentType='clamped' )
#cmds.keyTangent( 'Hand_Right', inTangentType='linear', outTangentType='linear' )