//----------------------------------------------------------------------------------------------
//
//	SCRIPT:			icCRunlockAttr.mel
//
//	AUTHOR:			Ingo Clemens
//					www.braverabbit.de
//					www.braverabbit.de/playground
//
//	DATE:			Feb 07, 2009
//					created: Jan 02, 2005
//
//----------------------------------------------------------------------------------------------

//----------------------------------------------------------------------------------------------
//
//	USE AND MODIFY AT YOUR OWN RISK!!
//
//----------------------------------------------------------------------------------------------


//----------------------------------------------------------------------------------------------
//
// unlock the given channels
//
//----------------------------------------------------------------------------------------------

global proc icCRunlockAttr ( string $currentNode, string $channelArray )
{
	string $lhChannel[];

	int $count = `tokenize $channelArray "," $lhChannel`;

	for ($item in $lhChannel)
	{
		setAttr -k 0 -l 0 ($currentNode + "." + $item);
	}
}
